services:
  spam_signal:
    command: bash -c "sleep infinity"
    image: octree/decidim-dev:0.29
    entrypoint: ""
    volumes:
      - .:/home/decidim/module
      - bundle:/home/decidim/app/vendor
      - node_modules:/home/decidim/app/node_modules
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://decidim:pleaseChangeMe@spam-signal-pg:5432/decidim
      - DATABASE_HOST=spam-signal-pg
      - DATABASE_USERNAME=decidim
      - DATABASE_PASSWORD=pleaseChangeMe
      - DEV_MODULE=decidim-spam_signal
      - RAILS_ENV=development
      - DISABLED_DOCKER_COMPOSE = true # To run tests in docker
    depends_on:
      - spam-signal-pg
    ports:
      - 3000:3000
    links:
      - spam-signal-pg

  spam-signal-pg:
    image: postgres:15
    volumes:
      - spam_signal-pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DATABASE=decidim
      - POSTGRES_USER=decidim
      - POSTGRES_PASSWORD=pleaseChangeMe

volumes:
  node_modules: {}
  bundle: {}
  spam_signal-pg-data: {}
